# -*- coding: utf-8 -*-
"""Task 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MA5SRoZwURhSvQeZt6NFxdCU75efRiAJ
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df5=pd.read_csv("/content/sample_data/RTA Dataset.csv")

df5.head()
df5.describe()

df5.isnull().sum()

df5.bfill(inplace=True)
df5.isnull().sum()

df5['Hour']=pd.to_datetime(df5['Time'],format='%H:%M:%S').dt.hour

plt.figure(figsize=(8,4))
sns.countplot(x='Hour',data=df5, hue='Hour',palette='magma',legend=False)
plt.title('Number of Accidents per Hour')
plt.xlabel('Hour of the day')
plt.ylabel('Number of accidents')
plt.show()

plt.figure(figsize=(8,4))
sns.countplot(x='Day_of_week',data=df5, hue='Day_of_week', palette='magma',legend=False)
plt.title('Number of Accidents per Day Of The Week')
plt.xlabel('Day Of The Week')
plt.ylabel('Number of accidents')
plt.show()

plt.figure(figsize=(8,4))
sns.countplot(x='Age_band_of_driver',data=df5, hue='Age_band_of_driver', palette='magma',legend=False)
plt.title('Number of Accidents per Age band Of Driver')
plt.xlabel('Age Band of Driver')
plt.ylabel('Number of accidents')
plt.show()

plt.figure(figsize=(8,4))
sns.countplot(x='Hour',data=df5, hue='Hour', palette='magma',legend=False)
plt.title('Number of Accidents per Hour')
plt.xlabel('Hour of the day')
plt.ylabel('Number of accidents')
plt.show()

plt.figure(figsize=(8,4))
sns.countplot(x='Day_of_week',data=df5, hue='Day_of_week', palette='magma',legend=False)
plt.title('Number of Accidents per Day of the Week')
plt.xlabel('Day Of The Week')
plt.ylabel('Number of accidents')
plt.show()